<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0SJ3B8VU" failures="1" tests="1" name="Default test" time="0.043" errors="0" timestamp="27 Aug 2021 09:11:33 GMT">
  <testcase classname="com.inetbanking.testCases.TC_RagisterUser_004" name="ragisterNewCustomer" time="0.014">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	driver cannot be resolved to a variable
	logger cannot be resolved
	driver cannot be resolved
	baseURL2 cannot be resolved to a variable
	logger cannot be resolved
	driver cannot be resolved
	logger cannot be resolved
	The method randomString() is undefined for the type TC_RagisterUser_004
	The method randomString() is undefined for the type TC_RagisterUser_004
	logger cannot be resolved
	driver cannot be resolved
	logger cannot be resolved
	driver cannot be resolved to a variable
	logger cannot be resolved
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
driver cannot be resolved to a variable
logger cannot be resolved
driver cannot be resolved
baseURL2 cannot be resolved to a variable
logger cannot be resolved
driver cannot be resolved
logger cannot be resolved
The method randomString() is undefined for the type TC_RagisterUser_004
The method randomString() is undefined for the type TC_RagisterUser_004
logger cannot be resolved
driver cannot be resolved
logger cannot be resolved
driver cannot be resolved to a variable
logger cannot be resolved

at com.inetbanking.testCases.TC_RagisterUser_004.ragisterNewCustomer(TC_RagisterUser_004.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ragisterNewCustomer -->
</testsuite> <!-- Default test -->
